// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLG3eQJXMBD8E3PVZT7euTcUGRKfuDTG0',
    appId: '1:152167280912:android:1eaae2e5637e163550b595',
    messagingSenderId: '152167280912',
    projectId: 'dubchak-practice-project-4bcdf',
    storageBucket: 'dubchak-practice-project-4bcdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQL33oMxZVE4lmamk9vcaYpCVMHvrS3pA',
    appId: '1:152167280912:ios:60690fcc8048a1c650b595',
    messagingSenderId: '152167280912',
    projectId: 'dubchak-practice-project-4bcdf',
    storageBucket: 'dubchak-practice-project-4bcdf.appspot.com',
    iosClientId: '152167280912-20m0v9upjqmsb46a9882der9l0of2kcg.apps.googleusercontent.com',
    iosBundleId: 'com.example.dubchakPracticeProject',
  );
}
